# Generated by Django 4.1.5 on 2023-01-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_participant_note_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.lesson'),
            preserve_default=False,
        ),
    ]
